export enum PacketType {
    MessageSelect = 'M',
    DeleteMessageText = 'C',
    UpdateMessageText = 'T',
    SetMessageParameters = 'P',
    DeleteUserFieldData = 'D',
    UpdateUserFieldData = 'U',
    UpdateLogoData = 'L',
    SetModuleWidths = 'B',
    StartJet = 'J',
    StopJet = 'K',
    RequestPartNumber = 'H',
    RequestErrorStatus = 'E',
    SetDateAndTime = 'Z',
    RequestCurrentSelectedMessage = 'Q',
    PrintOnOff = 'O',
    RequestPrintProductCounter = 'G',
    ResetPrintProductCounter = 'R',
}
